version: "3.9"
services:
  worker:
    build:
      context: ./fetcher
      dockerfile: Dockerfile.worker
    command: python fetch_coinryze.py
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    restart: always

  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    restart: always
