services:
  - type: web
    name: coinryze-worker-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn fetcher.worker_server:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: FETCH_INTERVAL_MIN
        value: "1"
