services:
  - type: web
    name: coinryze-dashboard
    env: docker
    dockerfilePath: ./Dockerfile.streamlit
    plan: free
    autoDeploy: true
    envVars:
      - key: BACKEND_URL
        value: https://coinryze-backend.onrender.com
      - key: CSV_PATH
        value: /app/frontend/coinryze_history.csv

  - type: web
    name: coinryze-backend
    env: docker
    dockerfilePath: ./Dockerfile.backend
    plan: free
    autoDeploy: true
    envVars:
      - key: MODEL_PATH
        value: /app/models/rf_model.joblib
