FROM python:3.10-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend .

ENV PORT=10000
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "10000"]
