FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY fetcher/ ./fetcher/
COPY frontend/ ./frontend/
CMD ["python","-u","fetcher/fetch_coinryze.py"]
